// EDITOR SUBLIME
class prog
{
	public static void main(String args[])
	{
		   int i,j;
           kriti: for(i=1;i<=10;i++)
            {
                System.out.println();

                ruby:for(j=1;j<=10;j++)
                {
                    System.out.print(j + " ");

                    if(j==5)
                        break ruby;          //Statement 1
                }
            }
        
    }

}